###

@server=http://localhost:4243

###

GET {{server}}/products/allProducts

###

GET {{server}}/products/availableProducts

###

GET {{server}}/products/unavailableProducts

###

GET {{server}}/products/displayProducts

###

GET {{server}}/products/highestToLowestPrice

###

GET {{server}}/products/lowestToHighestPrice

###

GET {{server}}/products/category/3

###

GET {{server}}/products/individual/10

###

GET {{server}}/products/deals/Monday

###

POST {{server}}/products/addProduct
Content-Type: application/json

{
    "data":{
        "productName": "Glassy",
        "productImage": "https://www.momijibeauty.com/cdn/shop/files/MOMIJI-Glassy-01.jpg?v=1704230259&width=2048",
        "productSummary": "Glassy is a moisturizing cream with a gel texture that hydrates, moisturizes, softens, comforts, illuminates and protects your skin from external aggressors.",
        "productDescription": "We wanted a moisturizer that would fulfill your dreams: hydrate, moisturize, soften, comfort, illuminate and protect from external aggressors. So we created Glassy, ​​the new step in the Momiji routine that does all that with the help of antioxidants, peptides and triple hyaluronic acid.",
        "price": 28,
        "availability": 1,
        "display": 1,
        "categoryID": 1
    }
}

###

PUT {{server}}/product/24
Content-Type: application/json

{
    "data":{
        "productName": "Product Update",
        "productImage": "bla",
        "productSummary": "bla",
        "productDescription": "bla",
        "price": 2,
        "availability": 1,
        "display": 1,
        "categoryID": 3
    }
}

###

PUT {{server}}/product/updatePrice/4
Content-Type: application/json

{
    "data":{
        "price": 40
    }
}

###

PUT {{server}}/product/updateDeal/10
Content-Type: application/json

{
    "data":{
        "deal": "50% off"
    }
}

###

DELETE {{server}}/product/24

